image: ${CI_REGISTRY}/yamaha-bps/bps_ros_pipelines/core

before_script:
  - git -C ${CI_BUILDS_DIR} clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/yamaha-bps/bps_ros_pipelines.git
  - source ${CI_BUILDS_DIR}/bps_ros_pipelines/bpsci-before.bash

after_script:
  - source ${CI_BUILDS_DIR}/bps_ros_pipelines/bpsci-after.bash

build:
  stage: build
  script:
    - colcon build --packages-up-to $(colcon list -n --base-paths ${CI_PROJECT_DIR})
  artifacts:
    paths: [build/, install/]
    expire_in: 1 day
  cache:
    paths: [ccache/]
  only: [master, merge_requests, tags, web]

test:
  stage: test
  script:
    - colcon test --packages-select $(colcon list -n --base-paths ${CI_PROJECT_DIR})
    - colcon test-result
  artifacts:
    reports:
      junit: [build/*/test_results/*/*.xml]
    expire_in: 1 week
  only: [master, merge_requests, tags, web]
